#repr(object)
print(repr(1))
print(repr('a'))
a = 'abc'
print(repr(a))
print(repr(object))
print(repr([1,2,3]))
print(repr((1,2,3)))
print(repr({'k', 'v'}))
print(repr(frozenset([1,2,3])))
print(repr(set([1,2,3])))
print(repr(range(5)))
